### ISSUE TITLE
dmd 2.101 cannot build ddbc

### ISSUE THREAD

**Issue by XinViet** [buggins/ddbc#112]
dmd 2.101 cannot build ddbc

https://dlang.org/changelog/2.101.0.html#logger_remove_compile_time_loglevel
https://dlang.org/changelog/2.101.0.html#logger_sharedLog_returning_shared_logger

**Comment by vnayar** [comment]
I encountered the same problem and created a pull request in response: https://github.com/buggins/ddbc/pull/113

**Comment by vnayar** [comment]
@SingingBush released a fix for this issue in v0.5.7.
