### ISSUE TITLE
MySQL update DateTime error: 0001-Jan-01 00:00:00

### ISSUE THREAD

**Issue by xucs007** [buggins/ddbc#129]
[main(QJSo) INF] ddbc.core.SQLException@../ddbc/source/ddbc/drivers/mysqlddbc.d(###): MySQL error: Incorrect datetime value: '0001-Jan-01 00:00:00' 

In pods.d, the addFieldValue(T)(), and addUpdateValue(T)() functions, need handle DateTime value separately,
not simply to!string - I couldn't figure out an elegant way right now, just stupidly check if my field name ends with a "_time" or not.

**Comment by xucs007** [comment]
My own mistake, I'll close

**Comment by SingingBush** [comment]
I suspect the code to write the string value also needs to check member type the same way _getColumnTypeDatasetReadCodeByName_ does and if it's a datetime then ensure ISO format when writing the string to ensure it works regardless of locale settings.

**Comment by xucs007** [comment]
Thanks for your information. I've submitted a pull request. Can somebody take a quick look? Just 10-20 lines of code.

**Comment by xucs007** [comment]
Thanks for your information. I've submitted a pull request. Can somebody take a quick look? Just 10-20 lines of code.

**Comment by SingingBush** [comment]
Fixed by https://github.com/buggins/ddbc/commit/ec173284307f8be42e29b009979d250ffe71229f in PR #132
