### ISSUE TITLE
Error: no property 'select' for type 'ddbc.core. Statement'

### ISSUE THREAD

**Issue by bubnenkoff** [buggins/ddbc#18]
I can't understand what I am doing wrong. Code example show:
```
// our POD object
struct User {
    long id;
    string name;
    int flags;
}

writeln("reading all user table rows");
foreach(ref e; stmt.select!User) {
    writeln("id:", e.id, " name:", e.name, " flags:", e.flags);
}
```
this in my case work fine:
```auto newimages = db.stmt.executeQuery(sql);```

But when I am trying this:

```
		foreach(ref e; db.stmt.select!DBData)
		{

		}
```

I am getting error: `Error: no property 'select' for type 'ddbc.core.Statement'`. What's wrong?

**Comment by bubnenkoff** [comment]
Posted question here http://forum.dlang.org/thread/frapdxdjpiwrjwjhzufu@forum.dlang.org

**Comment by buggins** [comment]
You forgot to add "import ddbc.pods;"
