### ISSUE TITLE
Can't get bytea from postgres

### ISSUE THREAD

**Issue by bubnenkoff** [buggins/ddbc#26]
The topic is there http://stackoverflow.com/questions/36469669/how-to-load-unload-binary-blob-from-postgresql-with-d
http://img.ctrlv.in/img/16/04/07/57063cd3dc645.png
Possible it's DDBC bug.

**Comment by buggins** [comment]
ubytesToBytea should be fixed

**Comment by buggins** [comment]
Fixed
