### ISSUE TITLE
PostgreSQL 9.5 Beta 1 no longer supports autocommit option

### ISSUE THREAD

**Issue by bhechinger** [buggins/ddbc#29]
It looks like this has been removed:

http://www.postgresql.org/docs/9.5/static/release-9-5.html
"Remove server configuration parameter autocommit, which was already deprecated and non-operational (Tom Lane)"

I took a quick stab at making this configurable but quickly ran amuck and gave in. I have a local copy checked out where I just comment out setAutoCommit(true); to make it work.

**Comment by buggins** [comment]
If no setAutoCommit is called, does it commit changes made by executeUpdate() if no conn.commit() is called?

**Comment by buggins** [comment]
It should be fixed in v0.2.33

Could you please confirm?
