### ISSUE TITLE
Feature Request: support for MS SQL

### ISSUE THREAD

**Issue by SingingBush** [buggins/ddbc#40]
I know this is a big ask but it would be great to have. And of course to then support it in hibernated.

**Comment by ephag** [comment]
MS SQL works fine for me, but the test are still not working on travis (locally they all passed). It could be fixed by adding a docker for sql-server to the travis. But I have no experience with travis and docker, and no time to learn it right now.

**Comment by SingingBush** [comment]
I only see drivers for sqlite, postgres, and MySQL. How is the configuration for MSSQL done? I can't find any mention of it in the project

**Comment by ephag** [comment]
There is an open pull-request: #39 
There is a driver for odbc

**Comment by SingingBush** [comment]
ah yes, cool. I don't think the travis build problem will be related. I'll take a look when I have a free evening this later this week.

**Comment by SingingBush** [comment]
@ephag ignore last comment, I hadn't seen that you have updated the travis file for using Microsofts docker image.

According to [this page](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-docker), the mssql image requires Docker Engine 1.8+ but afaik travis-ci uses an older version. I think it would be best to revert the travis file to just doing builds/tests as they were and perhaps considering using docker for testing as a separate issue/PR. There is always the option of using another testing environment for the docker stuff.

**Comment by ephag** [comment]
@SingingBush I have just reverted the changes to travis except the `libevent-dev` dependency, and removed the `ODBC` configuration from the `full` test configuration. But the test does not pass either. I saw you did some changes to the travis file too. Are there any other problems I do not know.

**Comment by SingingBush** [comment]
yeah, there's a problem with [LDC on OSX](https://travis-ci.org/SingingBush/ddbc/builds/200528080). I've tried a few thing but not sorted it.

**Comment by SingingBush** [comment]
@ephag I finally sorted the LDC on OSX problem #49, it turned out to be really trivial.

**Comment by bausshf** [comment]
Is this still relevant and/or is it just a travis issue?

**Comment by SingingBush** [comment]
MS SQL support was merged but it's not tested by CI

**Comment by ephag** [comment]
The problem was, that the docker-image for the sql-server did not work with the current version of travis at this time.
The tests succeeded locally.

**Comment by SingingBush** [comment]
@ephag could you rebase your branch with that sql-server docker test. It'd be good to try it again, perhaps using another CI service

**Comment by bausshf** [comment]
@ephag Any news regarding @SingingBush comment?

That test would be the last thing left, right?

**Comment by ephag** [comment]
I'm very busy at the moment. I will not have time to tackle it until September.

**Comment by SingingBush** [comment]
This issue has been kept open to keep track of the fact that we should add tests for MS SQL. Essentially putting back in the changes that got pulled out of ephag's fork:

https://github.com/ephag/ddbc/commit/fdeb8b1cc410ff3a2917014013eef7d482e6f9f7

I'll take a look at this.
