### ISSUE TITLE
PODs compile-time error when building in release mode

### ISSUE THREAD

**Issue by baklava151** [buggins/ddbc#60]
Using dub build --build=release with either ldc2 1.6.0 or dmd 2.078.0 gives the following when trying to use insert from pods.d

```
/home/chris/.dub/packages/ddbc-0.3.7/ddbc/source/ddbc/pods.d(436,9): Error: cannot interpret halt at compile time
/home/chris/.dub/packages/ddbc-0.3.7/ddbc/source/ddbc/pods.d(484,35):        called from here: getPropertyMemberType()
```

Making the assert on line 436 static seems to resolve this

**Comment by SingingBush** [comment]
this didn't cause an issue with current master on dmd 2.085 or dmd 2.089 but it makes sense to do so I'll make the change and push to master anyway.
