### ISSUE TITLE
Support std.datetime.systime.SysTime

### ISSUE THREAD

**Issue by zhaopuming** [buggins/ddbc#62]
`getDateTime` and `setDateTime` only support up to precision in seconds, but msecs and usecs are useful in many situations, and are supported by postegresql's timestamp type.

**Comment by SingingBush** [comment]
I've made a start on this but it'll take a while to write all the tests. It needs to be for all drivers so there's also the problem of ensuring that the CI is testing all db types

**Comment by SingingBush** [comment]
So far I've got this done for the SQLite driver in a [feature/systime branch on my fork](https://github.com/SingingBush/ddbc/tree/feature/systime). I'll continue with the remaining drivers when I can

**Comment by SingingBush** [comment]
This is now merged. See the example usage in [example/source/testddbc.d](https://github.com/buggins/ddbc/blob/master/example/source/testddbc.d)

@zhaopuming Could you build from the current master and give it a go.
